A	.github/workflows/biome.yml
A	.github/workflows/build.yml
M	.github/workflows/deploy.yml
A	README.md
A	README.webp
A	README.zh.md
M	astro.config.mjs
M	package.json
M	pnpm-lock.yaml
D	public/CNAME
A	public/assets/desktop-banner/d1.webp
A	public/assets/desktop-banner/d2.webp
A	public/assets/desktop-banner/d3.webp
A	public/assets/desktop-banner/d4.webp
A	public/assets/desktop-banner/d5.webp
A	public/assets/desktop-banner/d6.webp
A	public/assets/desktop-banner/d7.webp
A	public/assets/desktop-banner/d8.webp
D	public/assets/desktop/d1-ATRI.png
A	public/assets/home/home.png
D	"public/assets/home/\351\234\262\345\250\234\350\204\270\347\272\242-\345\234\206\345\275\242.png"
A	public/assets/mobile-banner/m1.webp
A	public/assets/mobile-banner/m2.webp
A	public/assets/mobile-banner/m3.webp
A	public/assets/mobile-banner/m4.webp
A	public/assets/mobile-banner/m5.webp
A	public/assets/mobile-banner/m6.webp
A	public/assets/mobile-banner/m7.webp
A	public/assets/mobile-banner/m8.webp
D	"public/assets/mobile/m1-\346\227\245\346\227\245\345\247\254.png"
A	public/assets/music/cover/cl.jpg
A	public/assets/music/cover/hitori.jpg
A	public/assets/music/cover/xryx.jpg
A	public/assets/music/url/cl.mp3
A	public/assets/music/url/hitori.mp3
A	public/assets/music/url/xryx.mp3
A	public/favicon/favicon-dark-128.png
A	public/favicon/favicon-dark-180.png
A	public/favicon/favicon-dark-192.png
A	public/favicon/favicon-dark-32.png
A	public/favicon/favicon-light-128.png
A	public/favicon/favicon-light-180.png
A	public/favicon/favicon-light-192.png
A	public/favicon/favicon-light-32.png
D	"public/favicon/\345\221\206\345\224\257.jpg"
D	public/images/albums/Acg/info.json
A	public/images/albums/AcgExample/464b547c424f36e7c6c38e0c2c151759a3bc68ec.jpg
A	public/images/albums/AcgExample/4986499bffa3b14c572c22c1ce441fc2cd94d63f.jpg
A	public/images/albums/AcgExample/5d662a33907ffe4edd7261ea4b374ff0a01e2dde.jpg
A	public/images/albums/AcgExample/91ae6186d2cf1af536b57c78ad7134ca1c8cbfe0.jpg
A	public/images/albums/AcgExample/9263a5edd8e9dab6d83ecf93029c197e3370b11e.jpg
A	public/images/albums/AcgExample/ca3c3f88c47fac7bdda5b8b29ca638dcee769704.jpg
A	public/images/albums/AcgExample/cover.jpg
A	public/images/albums/AcgExample/d1.webp
A	public/images/albums/AcgExample/d2.webp
A	public/images/albums/AcgExample/d3.webp
A	public/images/albums/AcgExample/d4.webp
A	public/images/albums/AcgExample/d5.webp
A	public/images/albums/AcgExample/d6.webp
A	public/images/albums/AcgExample/d7.webp
A	public/images/albums/AcgExample/d8.webp
A	public/images/albums/AcgExample/fd450b78411a7548183aa291bb4cbb99d0bc2bed.jpg
A	public/images/albums/AcgExample/info.json
A	public/images/albums/ExternalExample/info.json
A	public/images/albums/HiddenExample/info.json
A	public/images/diary/1.jpg
A	public/images/diary/sakura.jpg
A	src/assets/images/1.webp
D	src/assets/images/adore.png
A	src/assets/images/avatar.webp
A	src/assets/images/banner.webp
A	src/assets/images/demo-banner.png
M	src/components/Footer.astro
M	src/components/PostPage.astro
M	src/config.ts
M	src/constants/icon.ts
A	src/content/posts/draft.md
A	src/content/posts/encrypted-post.md
A	src/content/posts/markdown-extended.md
A	src/content/posts/markdown-mermaid.md
A	src/content/posts/markdown-tutorial.md
D	src/content/posts/markdown.md
A	src/content/posts/video.md
D	src/data/albums.ts
M	src/i18n/languages/zh_CN.ts
M	src/layouts/Layout.astro
A	src/pages/albums/[id]/index.astro
M	src/pages/atom.astro
M	src/pages/rss.astro
M	src/styles/main.css
A	src/styles/mobile-post-list-fix.css
M	src/utils/album-scanner.ts
